Repository Assault-Lily/LuciaDB, pull requests merged in 2021-05, with the labels that each got.

#29 LGエイルのメンバーを追加
  RDFs/legion.rdf
  RDFs/lily_yurigaoka.rdf
Labels: new entity

#32 既存のリリィに情報を追加
  RDFs/lily_alchemilla.rdf
  RDFs/lily_erensuge.rdf
  RDFs/lily_odaiba.rdf
  RDFs/lily_ryuto.rdf
  RDFs/lily_yurigaoka.rdf
Labels: enhancement

#38 LGヴィーンゴールヴ、LGシグルドリーヴァを追加。
  RDFs/legion.rdf
  RDFs/lily_yurigaoka.rdf
  RDFs/taskforce.rdf
Labels: enhancement, new entity

#39 吉田鳳蝶を追加。LGヘルフィヨトゥルを追加。
  RDFs/legion.rdf
  RDFs/lily_yurigaoka.rdf
Labels: new entity
